<?php
session_start();
$date=$_GET['date'];
$date1=$_GET['date1'];
$date2=$_GET['date2'];
if(!isset($_SESSION['user'])){
    header("location:index.php");
}

include('pdf/fpdf.php');


class PDF extends FPDF
{
// Page header
function Header()
{
    $this->SetFont('COURIER','B',15);
$this->Ln(10);
$company=strtoupper($_SESSION['company']);
$this->Cell(100,10,$company,0,1);
    $this->Cell(100,10,"RESPECTIVE EXPENSES REPORT",0,0);    
    
}
//page footer
function Footer()
{
    $this->SetY(-15);
    $this->SetFont('arial','I',10);
    $this->Cell(160,10,'Report generated by IREME Tech grp.',0,0,'C');
    $this->Cell(0,10,''.$this->PageNo().'/{nb}',0,0,'C');
}
}

$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('COURIER','B',15);


if($date1!="" && $date2!=""){
    $pdf->cell(100,8," ".$date1." to ".$date2,0,1);
}
elseif($date!=""){
    $pdf->cell(100,8,"On ".$date,0,1);
}


$pdf->Ln(15);
$pdf->SetFont('ARIAL','',12);
include "connection.php";

$select=mysqli_query($connect,"SELECT * from expenses where date='$date' or date between '$date1' and '$date2' order by date");
$pdf->SetFont('arial','B',12);
$pdf->cell(10,10,"No",1,0);
$pdf->cell(60,10,"Expenses",1,0);
$pdf->cell(40,10,"Amount",1,0);
$pdf->cell(40,10,"Date",1,0);
$pdf->cell(20,10,"Person",1,1);
$pdf->SetFont('ARIAL','',15);
$no=1;
$tot=0;
if(mysqli_num_rows($select)==0){
    $pdf->cell(170,10,"No Data Found!",1,1);
}
$pdf->SetFont('ARIAL','',12);
while($info=mysqli_fetch_array($select)){
    $amount=$info['amount'];
    $tot+=$amount;
                    $pdf->cell(10,8,$no.".",1,0);
                    $pdf->cell(60,8,$info['expense'],1,0);
                    $pdf->cell(40,8,$amount." Rwf",1,0);
                    $pdf->cell(40,8,$info['date'],1,0);
                    $pdf->cell(20,8,$info['person'],1,1);
                    $no++;
    }
    $pdf->SetFont('COURIER','',14);
    $pdf->cell(80,15,"TODAY TOTAL AMOUNT: ".$tot." Rwf",0,1);

$pdf->Output();
?>