<?php
session_start();
$date=$_GET['date'];
$date1=$_GET['date1'];
$date2=$_GET['date2'];
if(!isset($_SESSION['user'])){
    header("location:index.php");
}

include('pdf/fpdf.php');


class PDF extends FPDF
{
    // Page header
    function Header()
    {
        $this->SetFont('COURIER','B',15);
        $this->Ln(10);
        $company=strtoupper($_SESSION['company']);
    $this->Cell(100,10,$company,0,1);
    $this->Cell(100,10,"RESPECTIVE GENERAL REPORT",0,0);    
    
}
//page footer
function Footer()
{
    $this->SetY(-15);
    $this->SetFont('arial','I',10);
    $this->Cell(160,10,'Report generated by IREME Tech grp.',0,0,'C');
    $this->Cell(0,10,''.$this->PageNo().'/{nb}',0,0,'C');
}
}

$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('COURIER','B',15);


if($date1!="" && $date2!=""){
    $pdf->cell(100,8," ".$date1." to ".$date2,0,1);
}
elseif($date!=""){
    $pdf->cell(100,8,"On ".$date,0,1);
}


$pdf->Ln(15);
$pdf->SetFont('ARIAL','',12);
include "connection.php";

$pdf->cell(180,6,".............IMPORT",1,1);
$select_import=mysqli_query($connect,"SELECT * from import,items where item=item_id and date='$date' or date between '$date1' and '$date2' order by date");
$pdf->SetFont('arial','B',10);
$pdf->cell(10,10,"No",1,0);
    $pdf->cell(60,10,"Items",1,0);
    $pdf->cell(30,10,"Quantity",1,0);
    $pdf->cell(40,10,"Amount",1,0);
    $pdf->cell(40,10,"Date",1,1);
    $pdf->SetFont('ARIAL','',12);
    $no=1;
    $tot2=0;
    if(mysqli_num_rows($select_import)==0){
        
        $pdf->cell(180,10,"No Data Found!",1,1);    
    }
    $tot3=0;
    while($info=mysqli_fetch_array($select_import)){
        $amount3=$info['amount'];
                        $pdf->cell(10,8,$no.".",1,0);
                        $pdf->cell(60,8,ucwords($info['item']),1,0);
                        $pdf->cell(30,8,$info['qty'],1,0);
                        $pdf->cell(40,8,$amount3." Rwf",1,0);
                        $pdf->cell(40,8,$info['date'],1,1);
                        $no++;
                        $tot3=$tot3+$amount3;
                    }
                    
                    
                        $pdf->cell(180,6,".............EXPENSES",1,1);
                        $select_expenses=mysqli_query($connect,"SELECT * from expenses where date='$date' or date between '$date1' and '$date2' order by date");
                    $pdf->SetFont('arial','B',10);
                    $pdf->cell(10,10,"No",1,0);
                    $pdf->cell(60,10,"Expenses",1,0);
                    $pdf->cell(25,10,"Amount",1,0);
                    $pdf->cell(60,10,"Person",1,0);
                    $pdf->cell(25,10,"Date",1,1);
                    $pdf->SetFont('ARIAL','',12);
                    $no=1;
                    $tot2=0;
                    if(mysqli_num_rows($select_expenses)==0){
                    
                        $pdf->cell(180,10,"No Data Found!",1,1);    
                    }
                    while($info=mysqli_fetch_array($select_expenses)){
                        $amount2=$info['amount'];
                                        $pdf->cell(10,8,$no.".",1,0);
                                        $pdf->cell(60,8,ucwords($info['expense']),1,0);
                                        $pdf->cell(25,8,$amount2." Rwf",1,0);
                                        $pdf->cell(60,8,$info['person'],1,0);
                                        $pdf->cell(25,8,$info['date'],1,1);
                                        $no++;
                                        $tot2=$tot2+$amount2;
                                    }
                                    
                                    $pdf->cell(180,6,".............SALES",1,1);
                                    $select_sales=mysqli_query($connect,"SELECT item,count(item),sum(amount),date from sales where date='$date' or date between '$date1' and '$date2' group by item");
                                    $pdf->SetFont('arial','B',10);
                                    $pdf->cell(10,10,"No",1,0);
                                    $pdf->cell(60,10,"Items",1,0);
                                    $pdf->cell(40,10,"Amount",1,0);
                                    $pdf->cell(30,10,"Clients",1,0);
                                    $pdf->cell(40,10,"Date",1,1);
                                    $pdf->SetFont('ARIAL','',12);
                                    $no=1;
                                    $tot1=0;
                                    if(mysqli_num_rows($select_sales)==0){
                                    
                                        $pdf->cell(180,10,"No Data Found!",1,1);    
                                    }
                                    while($info=mysqli_fetch_array($select_sales)){
                                        $amount1=$info['sum(amount)'];
                                        $item=$info['item'];
                                        $get_item=mysqli_query($connect,"SELECT * from items where item_id='$item'");
                                                        $itemi=mysqli_fetch_array($get_item);
                                                        $name=$itemi['name'];
                                    
                                                        $pdf->cell(10,8,$no.".",1,0);
                                                        $pdf->cell(60,8,ucwords($name),1,0);
                                                        $pdf->cell(40,8,$amount1." Rwf",1,0);
                                                        $client=$info['count(item)'];
                                                        $pdf->cell(30,8,$client,1,0);
                                                        $pdf->cell(40,8,$info['date'],1,1);
                                                        $no++;
                                                        $tot1=$tot1+$amount1;
                                        }

    $pdf->SetFont('COURIER','',12);
    $tot=$tot1+$tot2+$tot3;
    $pdf->cell(180,15,"ToTal, IMPORT[".$tot3." Rwf] EXPENSES[".$tot2." Rwf] SALES[".$tot1." Rwf]",1,1);

$pdf->Output();
?>