<?php
session_start();
if(!isset($_SESSION['user'])){
    header("location:index.php");
}

include('pdf/fpdf.php');


class PDF extends FPDF
{
// Page header
function Header()
{
    $this->SetFont('COURIER','B',15);
$this->Ln(10);
$company=strtoupper($_SESSION['company']);
$this->Cell(100,10,$company,0,1);
    $this->Cell(100,10,'TODAY SALES REPORT',0,0);
    
    $this->Ln(15);
}
//page footer
function Footer()
{
    $this->SetY(-15);
    $this->SetFont('arial','I',10);
    $this->Cell(160,10,'Report generated by IREME Tech grp.',0,0,'C');
    $this->Cell(0,10,''.$this->PageNo().'/{nb}',0,0,'C');
}
}

$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('ARIAL','',12);
include "connection.php";

$get_date=mysqli_query($connect,"SELECT CURRENT_DATE as 'today'");
    $today=mysqli_fetch_array($get_date);
    $today_date=$today['today'];
    $select=mysqli_query($connect,"SELECT item,count(item),sum(amount),date from sales where date='$today_date' group by item");
$pdf->SetFont('arial','B',10);
$pdf->cell(10,10,"No",1,0);
$pdf->cell(40,10,"Items",1,0);
$pdf->cell(40,10,"Amount",1,0);
$pdf->cell(40,10,"Date",1,0);
$pdf->cell(40,10,"Clients",1,1);
$pdf->SetFont('ARIAL','B',15);
$no=1;
$tot=0;
if(mysqli_num_rows($select)==0){
    $pdf->cell(170,10,"No Data Found!",1,1,"C");
}
$pdf->SetFont('ARIAL','',12);
while($info=mysqli_fetch_array($select)){
    $amount=$info['sum(amount)'];
    $item=$info['item'];
    $get_item=mysqli_query($connect,"SELECT * from items where item_id='$item'");
                    $itemi=mysqli_fetch_array($get_item);
                    $name=$itemi['name'];

                    $pdf->cell(10,8,$no.".",1,0);
                    $pdf->cell(40,8,ucwords($name),1,0);
                    $pdf->cell(40,8,$amount." Rwf",1,0);
                    $pdf->cell(40,8,$info['date'],1,0);
                    $client=$info['count(item)'];
                    $pdf->cell(40,8,$client,1,1);
                    $no++;
                    $tot=$tot+$amount;
    }
    $pdf->SetFont('COURIER','',12);

    $cash=mysqli_query($connect,"SELECT sum(amount) from sales where date='$today_date' and payment='cash'");
      $cash_amount=mysqli_fetch_array($cash)['sum(amount)'];

      $momo=mysqli_query($connect,"SELECT sum(amount) from sales where date='$today_date' and payment='momo'");
      $momo_amount=mysqli_fetch_array($momo)['sum(amount)'];

      $credit=mysqli_query($connect,"SELECT sum(amount) from sales where date='$today_date' and payment='credit'");
      $credit_amount=mysqli_fetch_array($credit)['sum(amount)'];

      $pdf->cell(170,15,"TODAY AMOUNT: ".$tot." Rwf CASH[".$cash_amount.".0], MOMO[".$momo_amount.".0], CREDIT[".$credit_amount.".0]",0,1);

$pdf->Output();
?>