<?php
session_start();
if(!isset($_SESSION['user'])){
    header("location:index.php");
}

include('pdf/fpdf.php');


class PDF extends FPDF
{
// Page header
function Header()
{
    $this->SetFont('COURIER','B',15);
$this->Ln(10);
$company=strtoupper($_SESSION['company']);
$this->Cell(100,10,$company,0,1);
    $this->Cell(100,10,'TODAY EXPENSES REPORT',0,0);
    
    $this->Ln(15);
}
//page footer
function Footer()
{
    $this->SetY(-15);
    $this->SetFont('arial','I',10);
    $this->Cell(160,10,'Report generated by IREME Tech grp.',0,0,'C');
    $this->Cell(0,10,''.$this->PageNo().'/{nb}',0,0,'C');
}
}

$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('ARIAL','',12);
include "connection.php";

$get_date=mysqli_query($connect,"SELECT CURRENT_DATE as 'today'");
    $today=mysqli_fetch_array($get_date);
    $todaty_date=$today['today'];
$select=mysqli_query($connect,"SELECT * from expenses where date='$today_date' order by date");
$pdf->SetFont('arial','B',10);
$pdf->cell(10,10,"No",1,0);
$pdf->cell(40,10,"Items",1,0);
$pdf->cell(40,10,"Amount",1,0);
$pdf->cell(40,10,"Date",1,0);
$pdf->cell(40,10,"Clients",1,1);
$pdf->SetFont('ARIAL','',15);
$no=1;
$tot=0;
if(mysqli_num_rows($select)==0){
    $pdf->cell(170,10,"No Data Found!",1,1);
}
$pdf->SetFont('ARIAL','',12);
while($info=mysqli_fetch_array($select)){
    $amount=$info['amount'];
                    $pdf->cell(10,8,$no.".",1,0);
                    $pdf->cell(40,8,$info['description'],1,0);
                    $pdf->cell(40,8,$amount." Rwf",1,0);
                    $pdf->cell(40,8,$info['date'],1,0);
                    $pdf->cell(40,8,$info['person'],1,1);
                    $no++;
                    $tot=$tot+$amount;
    }
    $pdf->SetFont('COURIER','',14);
    $pdf->cell(80,15,"TODAY TOTAL AMOUNT: ".$tot." Rwf",0,1);

$pdf->Output();
?>